2025-01-12 15:18:33,946 - INFO - Starting bot...
2025-01-12 15:18:35,154 - INFO - Application started
2025-01-12 15:18:59,094 - INFO - Application is stopping. This might take a moment.
2025-01-12 15:18:59,094 - INFO - Application.stop() complete
2025-01-12 15:19:01,531 - INFO - Starting bot...
2025-01-12 15:19:02,511 - INFO - Application started
2025-01-12 15:19:13,421 - INFO - Application is stopping. This might take a moment.
2025-01-12 15:19:13,421 - INFO - Application.stop() complete
2025-01-12 15:19:16,124 - INFO - Starting bot...
2025-01-12 15:19:17,343 - INFO - Application started
2025-01-12 15:19:44,059 - INFO - Subscribing to new token creation events...
2025-01-12 15:21:51,181 - INFO - Application is stopping. This might take a moment.
2025-01-12 15:21:51,181 - INFO - Application.stop() complete
2025-01-12 15:21:53,917 - INFO - Starting bot...
2025-01-12 15:21:54,992 - INFO - Application started
2025-01-12 15:22:05,603 - INFO - Subscribing to new token creation events...
2025-01-12 15:22:10,751 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-17' coro=<check_same_token_availability() done, defined at /home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py:404> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 424, in check_same_token_availability
    send_telegram_message_if_found_a_trending_token(unique_tokens,total_tokens_count,token_symbol,token_name,contract_address)
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 448, in send_telegram_message_if_found_a_trending_token
    if unique_tokens[0].get("contract_address")== contract_address :
       ~~~~~~~~~~~~~^^^
IndexError: list index out of range
2025-01-12 15:22:10,849 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-18' coro=<check_same_token_availability() done, defined at /home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py:404> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 424, in check_same_token_availability
    send_telegram_message_if_found_a_trending_token(unique_tokens,total_tokens_count,token_symbol,token_name,contract_address)
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 448, in send_telegram_message_if_found_a_trending_token
    if unique_tokens[0].get("contract_address")== contract_address :
       ~~~~~~~~~~~~~^^^
IndexError: list index out of range
2025-01-12 15:22:34,673 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-27' coro=<check_same_token_availability() done, defined at /home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py:404> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 424, in check_same_token_availability
    send_telegram_message_if_found_a_trending_token(unique_tokens,total_tokens_count,token_symbol,token_name,contract_address)
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 448, in send_telegram_message_if_found_a_trending_token
    if unique_tokens[0].get("contract_address")== contract_address :
       ~~~~~~~~~~~~~^^^
IndexError: list index out of range
2025-01-12 15:22:42,554 - INFO - Application is stopping. This might take a moment.
2025-01-12 15:22:42,555 - INFO - Application.stop() complete
2025-01-12 15:26:08,335 - INFO - Starting bot...
2025-01-12 15:26:09,323 - INFO - Application started
2025-01-12 15:26:24,869 - INFO - Subscribing to new token creation events...
2025-01-12 15:30:01,476 - INFO - Application is stopping. This might take a moment.
2025-01-12 15:30:01,477 - INFO - Application.stop() complete
2025-01-12 16:14:35,430 - INFO - Starting bot...
2025-01-12 16:14:36,533 - INFO - Application started
2025-01-12 16:15:25,993 - INFO - Subscribing to new token creation events...
2025-01-12 16:15:27,653 - INFO - Successfully added token PARK CHANYEOL to the database.
2025-01-12 16:15:27,992 - ERROR - Error adding token data to database: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2025-01-12 16:15:33,673 - ERROR - Error adding token data to database: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2025-01-12 16:15:34,020 - INFO - Successfully added token Green MAn to the database.
2025-01-12 16:15:35,364 - INFO - Successfully added token PIMPLE to the database.
2025-01-12 16:15:37,605 - ERROR - Error adding token data to database: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2025-01-12 16:15:41,876 - INFO - Successfully added token New Baby Lion to the database.
2025-01-12 16:15:46,567 - ERROR - Error adding token data to database: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2025-01-12 16:15:47,364 - INFO - Successfully added token Solana Wif Hat to the database.
2025-01-12 16:15:48,697 - ERROR - Error adding token data to database: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2025-01-12 16:15:48,954 - ERROR - Error adding token data to database: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2025-01-12 16:15:48,955 - INFO - Application is stopping. This might take a moment.
2025-01-12 16:15:48,955 - INFO - Application.stop() complete
2025-01-12 16:23:02,235 - INFO - Starting bot...
2025-01-12 16:23:03,674 - INFO - Application started
2025-01-12 16:23:15,065 - INFO - Subscribing to new token creation events...
2025-01-12 16:23:16,383 - INFO - Successfully added token GloryBOX to the database.
2025-01-12 16:23:17,394 - INFO - Successfully added token Foliel to the database.
2025-01-12 16:23:20,471 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:23:20,772 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:23:23,594 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:23:26,805 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:23:30,394 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:23:30,772 - ERROR - Error adding token data to database: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2025-01-12 16:23:31,150 - INFO - Successfully added token LyraverseAI to the database.
2025-01-12 16:23:44,095 - INFO - Successfully added token Frank the Sawfish to the database.
2025-01-12 16:23:45,728 - INFO - Successfully added token Nice Fucking Ass to the database.
2025-01-12 16:23:47,112 - ERROR - Error adding token data to database: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2025-01-12 16:23:48,261 - INFO - Successfully added token Ares AI to the database.
2025-01-12 16:23:51,839 - ERROR - Error adding token data to database: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2025-01-12 16:23:57,629 - INFO - Successfully added token Aria Dog to the database.
2025-01-12 16:23:58,484 - INFO - Successfully added token Baby Apetronaut to the database.
2025-01-12 16:23:59,295 - INFO - Successfully added token Kiyutsu AI to the database.
2025-01-12 16:24:06,484 - INFO - Successfully added token Fast to the database.
2025-01-12 16:24:15,162 - INFO - Successfully added token 2019 OG WIF to the database.
2025-01-12 16:24:16,045 - ERROR - Error adding token data to database: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2025-01-12 16:24:21,973 - INFO - Successfully added token Flame to the database.
2025-01-12 16:24:24,970 - INFO - Application is stopping. This might take a moment.
2025-01-12 16:24:24,971 - INFO - Application.stop() complete
2025-01-12 16:26:25,993 - INFO - Starting bot...
2025-01-12 16:26:27,133 - INFO - Application started
2025-01-12 16:26:34,357 - INFO - Subscribing to new token creation events...
2025-01-12 16:26:36,413 - INFO - Successfully added token SupplyVest to the database.
2025-01-12 16:26:37,023 - INFO - Successfully added token Dog Wif Vodka to the database.
2025-01-12 16:26:37,924 - INFO - Successfully added token snAIke to the database.
2025-01-12 16:26:38,502 - INFO - Successfully added token Just an American WIF Guy to the database.
2025-01-12 16:26:43,302 - INFO - Successfully added token my first casino to the database.
2025-01-12 16:26:49,502 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:26:52,880 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:26:56,117 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:26:56,491 - INFO - Successfully added token locked in fented car to the database.
2025-01-12 16:26:59,414 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:27:02,024 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:27:02,402 - INFO - Successfully added token Creating Shareholder Value to the database.
2025-01-12 16:27:02,836 - INFO - Successfully added token Hat Wif Hat to the database.
2025-01-12 16:27:03,224 - INFO - Successfully added token SHIBA INU TOWEL to the database.
2025-01-12 16:27:03,580 - INFO - Successfully added token cat wif b(hat) to the database.
2025-01-12 16:27:03,980 - INFO - Successfully added token Leon the sea lion to the database.
2025-01-12 16:27:08,279 - INFO - Successfully added token Kihomi AI to the database.
2025-01-12 16:27:12,354 - INFO - Successfully added token Dino Wif Hat to the database.
2025-01-12 16:27:24,465 - INFO - Successfully added token Muslims to the database.
2025-01-12 16:27:27,137 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:27:27,782 - INFO - Successfully added token Liminaral to the database.
2025-01-12 16:27:31,782 - INFO - Successfully added token CHILLGUY WIF HAT to the database.
2025-01-12 16:27:32,177 - INFO - Successfully added token Dog wif Frog Hat to the database.
2025-01-12 16:27:34,154 - INFO - Successfully added token Octopus Network to the database.
2025-01-12 16:27:37,155 - INFO - Successfully added token shrek to the database.
2025-01-12 16:27:39,849 - INFO - Successfully added token MAVERICK AI to the database.
2025-01-12 16:27:40,193 - INFO - Successfully added token edurubio to the database.
2025-01-12 16:27:43,371 - INFO - Successfully added token NIMBLE Networks AI Infrastructur to the database.
2025-01-12 16:27:43,877 - INFO - Successfully added token Cobra+Cat  to the database.
2025-01-12 16:27:44,866 - INFO - Successfully added token Your World  AI to the database.
2025-01-12 16:27:49,488 - INFO - Successfully added token Kobe  to the database.
2025-01-12 16:27:51,183 - INFO - Successfully added token WTAD to the database.
2025-01-12 16:27:52,758 - INFO - Successfully added token SHAMAN coin to the database.
2025-01-12 16:28:02,411 - INFO - Successfully added token snAIke to the database.
2025-01-12 16:28:04,250 - INFO - Successfully added token EvZK to the database.
2025-01-12 16:28:05,672 - INFO - Successfully added token Trump  to the database.
2025-01-12 16:28:16,002 - INFO - Successfully added token Hoyumi AI to the database.
2025-01-12 16:28:21,705 - INFO - Successfully added token riley schoch graduating to the database.
2025-01-12 16:28:23,483 - INFO - Successfully added token Sberex to the database.
2025-01-12 16:28:24,427 - INFO - Successfully added token DUDU to the database.
2025-01-12 16:28:29,094 - INFO - Successfully added token dog wif c(hat) to the database.
2025-01-12 16:28:31,583 - INFO - Successfully added token MeteoraAG's Mascot to the database.
2025-01-12 16:28:31,905 - INFO - Successfully added token Fridon AI to the database.
2025-01-12 16:28:33,939 - INFO - Successfully added token SNOWBUNNY to the database.
2025-01-12 16:28:36,628 - INFO - Successfully added token Make Europe great again to the database.
2025-01-12 16:28:39,784 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:28:42,606 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:28:45,139 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:28:47,697 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:28:50,073 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:28:50,395 - INFO - Successfully added token CatFrog to the database.
2025-01-12 16:28:51,584 - INFO - Successfully added token first tokenized ETH name service to the database.
2025-01-12 16:28:51,951 - INFO - Successfully added token Astral AI to the database.
2025-01-12 16:28:52,251 - INFO - Successfully added token PEEHOLE to the database.
2025-01-12 16:28:52,584 - INFO - Successfully added token rynel to the database.
2025-01-12 16:28:52,895 - INFO - Successfully added token Cat wif Unicorn to the database.
2025-01-12 16:28:55,479 - INFO - Successfully added token Fast to the database.
2025-01-12 16:28:57,584 - INFO - Successfully added token Defend Decentralization to the database.
2025-01-12 16:28:59,495 - INFO - Successfully added token Hosemo AI to the database.
2025-01-12 16:29:00,784 - INFO - Successfully added token Dog wif f(hat) to the database.
2025-01-12 16:29:06,584 - INFO - Successfully added token ELON PUP to the database.
2025-01-12 16:29:10,073 - INFO - Successfully added token 1st Tokenized Solana Stock to the database.
2025-01-12 16:29:14,873 - INFO - Successfully added token Pussy Needs Liquidity to the database.
2025-01-12 16:29:15,284 - INFO - Successfully added token UseUniversalX to the database.
2025-01-12 16:29:15,964 - INFO - Successfully added token Dexter the chow to the database.
2025-01-12 16:29:18,307 - INFO - Successfully added token dog wif beer to the database.
2025-01-12 16:29:28,518 - INFO - Successfully added token dog wif b(hat) to the database.
2025-01-12 16:29:38,274 - INFO - Successfully added token Fridon AI to the database.
2025-01-12 16:29:38,763 - INFO - Successfully added token BRIK® Socket to the database.
2025-01-12 16:29:42,553 - INFO - Successfully added token CMD to the database.
2025-01-12 16:29:45,530 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:29:48,186 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:29:50,708 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:29:53,475 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:29:53,842 - INFO - Successfully added token Ineffable Gnostic Sex to the database.
2025-01-12 16:29:55,041 - INFO - Successfully added token COOLCAT to the database.
2025-01-12 16:30:00,623 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:30:01,167 - INFO - Successfully added token Shaking My Head the Whole Time to the database.
2025-01-12 16:30:05,801 - INFO - Successfully added token Crypto Support to the database.
2025-01-12 16:30:07,567 - INFO - Successfully added token Live24_Fun to the database.
2025-01-12 16:30:11,767 - INFO - Successfully added token GISNTIL to the database.
2025-01-12 16:30:17,379 - INFO - Successfully added token Fridon AI to the database.
2025-01-12 16:30:17,823 - INFO - Successfully added token dog wif diploma to the database.
2025-01-12 16:30:18,201 - INFO - Successfully added token dog wif frog(hat) to the database.
2025-01-12 16:30:18,568 - INFO - Successfully added token Nice Fucking Titties to the database.
2025-01-12 16:30:22,268 - INFO - Successfully added token Kamiyu AI to the database.
2025-01-12 16:30:27,857 - INFO - Successfully added token Trump Wif Hat  to the database.
2025-01-12 16:30:30,468 - INFO - Successfully added token Dogeking AI to the database.
2025-01-12 16:30:32,613 - INFO - Successfully added token Stop Buying AI Coins  to the database.
2025-01-12 16:30:32,991 - INFO - Successfully added token UIIAI UIIAI to the database.
2025-01-12 16:30:33,746 - INFO - Successfully added token Only HAT to the database.
2025-01-12 16:30:37,391 - INFO - Successfully added token Ares AI to the database.
2025-01-12 16:30:39,991 - INFO - Successfully added token Pump DUDU to the database.
2025-01-12 16:30:40,336 - INFO - Successfully added token Nacho Cat 🌮😹 to the database.
2025-01-12 16:30:43,235 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:30:46,276 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:30:49,116 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:30:51,838 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:30:52,817 - INFO - Token update - {count}
2025-01-12 16:30:53,205 - INFO - Successfully added token The Shocked Cat to the database.
2025-01-12 16:30:56,138 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:30:56,460 - INFO - Successfully added token Do the math to the database.
2025-01-12 16:30:57,005 - INFO - Successfully added token HP Lovecraft's Cat's Name to the database.
2025-01-12 16:30:57,360 - INFO - Successfully added token AI prototype to the database.
2025-01-12 16:30:57,738 - INFO - Successfully added token AIVIN to the database.
2025-01-12 16:31:03,224 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:31:03,605 - INFO - Successfully added token Nouns Esports to the database.
2025-01-12 16:31:05,091 - INFO - Successfully added token Kisana AI to the database.
2025-01-12 16:31:08,080 - INFO - Successfully added token SupplyVest to the database.
2025-01-12 16:31:09,146 - INFO - Successfully added token JINGWEI ART to the database.
2025-01-12 16:31:09,558 - INFO - Successfully added token snake wif hat to the database.
2025-01-12 16:31:20,947 - INFO - Successfully added token Your World  AI to the database.
2025-01-12 16:31:23,728 - INFO - Successfully added token Nice Fucking Ass to the database.
2025-01-12 16:31:26,437 - INFO - Failed to retrieve metadata. Status code: 403
2025-01-12 16:31:26,525 - INFO - Successfully added token APOLLO2025 to the database.
2025-01-12 16:31:29,214 - INFO - Successfully added token Love Brunettes to the database.
2025-01-12 16:31:29,613 - INFO - Successfully added token Vora Terminal AI to the database.
2025-01-12 16:31:30,012 - INFO - Successfully added token Messy with Dog Hat to the database.
2025-01-12 16:31:33,691 - INFO - Successfully added token Chunk RETURNS to the database.
2025-01-12 16:31:37,735 - INFO - Successfully added token girlfriend to the database.
2025-01-12 16:31:38,301 - INFO - Successfully added token Truth_terminals Trash Oracle to the database.
2025-01-12 16:31:41,713 - INFO - Successfully added token HAT to the database.
2025-01-12 16:31:45,946 - INFO - Successfully added token girlfriend to the database.
2025-01-12 16:31:47,257 - INFO - Successfully added token Kichitsu AI to the database.
2025-01-12 16:31:50,991 - INFO - Successfully added token Gary Gensler's Gone to the database.
2025-01-12 16:31:54,836 - INFO - Successfully added token Toly´s Cat Rug to the database.
2025-01-12 16:31:55,328 - INFO - Successfully added token Justice for Waylon to the database.
2025-01-12 16:32:02,447 - INFO - Successfully added token Latecoin to the database.
2025-01-12 16:32:12,070 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:32:12,603 - INFO - Successfully added token ChillBatman to the database.
2025-01-12 16:32:22,583 - INFO - Successfully added token Fast to the database.
2025-01-12 16:32:22,983 - INFO - Successfully added token Akatsuki Pepe to the database.
2025-01-12 16:32:29,604 - INFO - Successfully added token Nexus Ai  to the database.
2025-01-12 16:32:30,839 - INFO - Successfully added token Doge Wif Knife to the database.
2025-01-12 16:32:35,859 - INFO - Successfully added token SupplyVest to the database.
2025-01-12 16:32:36,263 - INFO - Successfully added token kily to the database.
2025-01-12 16:32:37,890 - INFO - Successfully added token Milky Way  to the database.
2025-01-12 16:32:43,335 - INFO - Successfully added token Kiyutsu AI to the database.
2025-01-12 16:32:43,668 - INFO - Successfully added token sandwich wif dog to the database.
2025-01-12 16:32:49,335 - INFO - Successfully added token Torus Network AI to the database.
2025-01-12 16:32:51,491 - INFO - Successfully added token Hello World! to the database.
2025-01-12 16:32:57,980 - INFO - Successfully added token UHGF to the database.
2025-01-12 16:32:58,391 - INFO - Successfully added token Sphere to the database.
2025-01-12 16:32:58,847 - INFO - Successfully added token Peepzilla to the database.
2025-01-12 16:33:10,925 - INFO - Successfully added token Snake wif hat to the database.
2025-01-12 16:33:14,992 - INFO - Successfully added token Nexus Ai to the database.
2025-01-12 16:33:17,014 - INFO - Successfully added token MWOAH AI to the database.
2025-01-12 16:33:20,270 - INFO - Successfully added token HUSBAND to the database.
2025-01-12 16:33:21,814 - INFO - Successfully added token NIGGA CAT to the database.
2025-01-12 16:33:23,936 - INFO - Successfully added token Megapunks to the database.
2025-01-12 16:33:25,697 - INFO - Successfully added token Vertical AI to the database.
2025-01-12 16:33:26,263 - INFO - Successfully added token Koyusa AI to the database.
2025-01-12 16:33:27,214 - INFO - Successfully added token MGHM to the database.
2025-01-12 16:33:27,881 - INFO - Successfully added token ethereum under dog to the database.
2025-01-12 16:33:28,237 - INFO - Successfully added token gfe to the database.
2025-01-12 16:33:32,552 - INFO - Successfully added token Side Bitch to the database.
2025-01-12 16:33:39,928 - INFO - Successfully added token BALOO Bot to the database.
2025-01-12 16:33:41,105 - INFO - Successfully added token Siski to the database.
2025-01-12 16:33:45,661 - INFO - Successfully added token BULDOG COIN to the database.
2025-01-12 16:33:50,334 - INFO - Application is stopping. This might take a moment.
2025-01-12 16:33:50,334 - INFO - Application.stop() complete
2025-01-12 16:35:21,198 - INFO - Starting bot...
2025-01-12 16:35:22,131 - INFO - Application started
2025-01-12 16:36:02,064 - INFO - Subscribing to new token creation events...
2025-01-12 16:36:04,901 - INFO - Successfully added token PRISM AI to the database.
2025-01-12 16:36:07,426 - INFO - Successfully added token unc to the database.
2025-01-12 16:36:10,215 - INFO - Successfully added token Fridon AI to the database.
2025-01-12 16:36:13,379 - INFO - Successfully added token Your World  AI to the database.
2025-01-12 16:36:16,379 - INFO - Successfully added token how much cat  to the database.
2025-01-12 16:36:18,968 - INFO - Successfully added token Venom Agent to the database.
2025-01-12 16:36:21,735 - INFO - Successfully added token nice cook to the database.
2025-01-12 16:36:24,568 - INFO - Successfully added token MOON to the database.
2025-01-12 16:36:27,235 - INFO - Successfully added token waifu to the database.
2025-01-12 16:36:29,979 - INFO - Successfully added token Hosato AI to the database.
2025-01-12 16:36:32,568 - INFO - Successfully added token luu wif hat to the database.
2025-01-12 16:36:35,658 - INFO - Successfully added token Nexus Ai  to the database.
2025-01-12 16:36:40,924 - INFO - Successfully added token capybara wif capybara to the database.
2025-01-12 16:36:43,658 - INFO - Successfully added token Most important event in history to the database.
2025-01-12 16:36:46,269 - INFO - Successfully added token dog wif hat wif cat wif hat to the database.
2025-01-12 16:36:48,836 - INFO - Successfully added token Instant AIPrompt  to the database.
2025-01-12 16:36:51,301 - INFO - Successfully added token daugther to the database.
2025-01-12 16:36:53,897 - INFO - Successfully added token cat wif dog to the database.
2025-01-12 16:36:56,542 - INFO - Successfully added token Decentralised Nigga Coin to the database.
2025-01-12 17:05:13,042 - INFO - Starting bot...
2025-01-12 17:05:14,134 - INFO - Application started
2025-01-12 17:06:25,578 - INFO - Subscribing to new token creation events...
2025-01-12 17:06:27,221 - ERROR - An error occurred: Invalid URL 'QmTRLroZ2bgQYxkkg1HYXxW7JDtrwTKUkY3WBdYgyH3jYq': No scheme supplied. Perhaps you meant http://QmTRLroZ2bgQYxkkg1HYXxW7JDtrwTKUkY3WBdYgyH3jYq?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 431, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'QmTRLroZ2bgQYxkkg1HYXxW7JDtrwTKUkY3WBdYgyH3jYq': No scheme supplied. Perhaps you meant http://QmTRLroZ2bgQYxkkg1HYXxW7JDtrwTKUkY3WBdYgyH3jYq?
2025-01-12 17:06:27,223 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:06:28,261 - ERROR - An error occurred: Invalid URL 'QmeJYPuF9Yz96WSydFgUwUiDn7i4GtZEAxXNkhQyGq9XjB': No scheme supplied. Perhaps you meant http://QmeJYPuF9Yz96WSydFgUwUiDn7i4GtZEAxXNkhQyGq9XjB?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 431, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'QmeJYPuF9Yz96WSydFgUwUiDn7i4GtZEAxXNkhQyGq9XjB': No scheme supplied. Perhaps you meant http://QmeJYPuF9Yz96WSydFgUwUiDn7i4GtZEAxXNkhQyGq9XjB?
2025-01-12 17:06:28,262 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:06:33,288 - ERROR - An error occurred: Invalid URL 'QmSP9CaENoVBVEHn6iC1z3JqP4faxPRtKXNGyC2YnURReq': No scheme supplied. Perhaps you meant http://QmSP9CaENoVBVEHn6iC1z3JqP4faxPRtKXNGyC2YnURReq?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 431, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'QmSP9CaENoVBVEHn6iC1z3JqP4faxPRtKXNGyC2YnURReq': No scheme supplied. Perhaps you meant http://QmSP9CaENoVBVEHn6iC1z3JqP4faxPRtKXNGyC2YnURReq?
2025-01-12 17:06:33,289 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:06:33,291 - ERROR - An error occurred: Invalid URL 'Qmaz5LqYYgY6vq9xVg4TdLUrLSip7DKnYyk5YyMuPz6U5u': No scheme supplied. Perhaps you meant http://Qmaz5LqYYgY6vq9xVg4TdLUrLSip7DKnYyk5YyMuPz6U5u?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 431, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'Qmaz5LqYYgY6vq9xVg4TdLUrLSip7DKnYyk5YyMuPz6U5u': No scheme supplied. Perhaps you meant http://Qmaz5LqYYgY6vq9xVg4TdLUrLSip7DKnYyk5YyMuPz6U5u?
2025-01-12 17:06:33,292 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:06:37,486 - ERROR - An error occurred: Invalid URL 'Qmcw1T2jMjCt9YTH2vHxkhASyB8SCW6bexrQ9q6kLSEP6A': No scheme supplied. Perhaps you meant http://Qmcw1T2jMjCt9YTH2vHxkhASyB8SCW6bexrQ9q6kLSEP6A?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 431, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'Qmcw1T2jMjCt9YTH2vHxkhASyB8SCW6bexrQ9q6kLSEP6A': No scheme supplied. Perhaps you meant http://Qmcw1T2jMjCt9YTH2vHxkhASyB8SCW6bexrQ9q6kLSEP6A?
2025-01-12 17:06:37,487 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:06:41,684 - ERROR - An error occurred: Invalid URL 'QmYzHAYrbxZnDYngvFzeFczhRNf616PNeNzN3zV1xppUNC': No scheme supplied. Perhaps you meant http://QmYzHAYrbxZnDYngvFzeFczhRNf616PNeNzN3zV1xppUNC?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 431, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'QmYzHAYrbxZnDYngvFzeFczhRNf616PNeNzN3zV1xppUNC': No scheme supplied. Perhaps you meant http://QmYzHAYrbxZnDYngvFzeFczhRNf616PNeNzN3zV1xppUNC?
2025-01-12 17:06:41,685 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:06:41,692 - ERROR - An error occurred: Invalid URL 'QmUbpvWpv8MqbZaE5i9d8G8PmRyjxTPJ57JUoqqRSEf7wQ': No scheme supplied. Perhaps you meant http://QmUbpvWpv8MqbZaE5i9d8G8PmRyjxTPJ57JUoqqRSEf7wQ?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 431, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'QmUbpvWpv8MqbZaE5i9d8G8PmRyjxTPJ57JUoqqRSEf7wQ': No scheme supplied. Perhaps you meant http://QmUbpvWpv8MqbZaE5i9d8G8PmRyjxTPJ57JUoqqRSEf7wQ?
2025-01-12 17:06:41,692 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:06:46,087 - ERROR - An error occurred: Invalid URL 'QmfHXNpRA1NgbqNeWjAkWwQsLRtAgwu7MYFuhKPYRDwW9b': No scheme supplied. Perhaps you meant http://QmfHXNpRA1NgbqNeWjAkWwQsLRtAgwu7MYFuhKPYRDwW9b?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 431, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'QmfHXNpRA1NgbqNeWjAkWwQsLRtAgwu7MYFuhKPYRDwW9b': No scheme supplied. Perhaps you meant http://QmfHXNpRA1NgbqNeWjAkWwQsLRtAgwu7MYFuhKPYRDwW9b?
2025-01-12 17:06:46,088 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:06:46,786 - ERROR - An error occurred: Invalid URL 'QmeYCiyQx2rzn1DbzHHMENyaF7zBQBE37KwHTbuQJPJeKc': No scheme supplied. Perhaps you meant http://QmeYCiyQx2rzn1DbzHHMENyaF7zBQBE37KwHTbuQJPJeKc?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 431, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'QmeYCiyQx2rzn1DbzHHMENyaF7zBQBE37KwHTbuQJPJeKc': No scheme supplied. Perhaps you meant http://QmeYCiyQx2rzn1DbzHHMENyaF7zBQBE37KwHTbuQJPJeKc?
2025-01-12 17:06:46,787 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:08:51,662 - INFO - Starting bot...
2025-01-12 17:08:52,860 - INFO - Application started
2025-01-12 17:09:07,216 - INFO - Application is stopping. This might take a moment.
2025-01-12 17:09:07,216 - INFO - Application.stop() complete
2025-01-12 17:09:10,017 - INFO - Starting bot...
2025-01-12 17:09:11,088 - INFO - Application started
2025-01-12 17:09:24,501 - INFO - Subscribing to new token creation events...
2025-01-12 17:09:27,061 - ERROR - An error occurred: Invalid URL 'QmSu763k2vWWSe9BtHwy7NgtCk5fRsmS8eSiLeZqknkNRG': No scheme supplied. Perhaps you meant http://QmSu763k2vWWSe9BtHwy7NgtCk5fRsmS8eSiLeZqknkNRG?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 432, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'QmSu763k2vWWSe9BtHwy7NgtCk5fRsmS8eSiLeZqknkNRG': No scheme supplied. Perhaps you meant http://QmSu763k2vWWSe9BtHwy7NgtCk5fRsmS8eSiLeZqknkNRG?
2025-01-12 17:09:27,063 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:09:33,205 - ERROR - An error occurred: Invalid URL 'QmXoNR9agbtgsWoAUE7sCPznoXuSwxLdut43Hhr577kb2c': No scheme supplied. Perhaps you meant http://QmXoNR9agbtgsWoAUE7sCPznoXuSwxLdut43Hhr577kb2c?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 432, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'QmXoNR9agbtgsWoAUE7sCPznoXuSwxLdut43Hhr577kb2c': No scheme supplied. Perhaps you meant http://QmXoNR9agbtgsWoAUE7sCPznoXuSwxLdut43Hhr577kb2c?
2025-01-12 17:09:33,206 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:09:49,180 - ERROR - An error occurred: Invalid URL 'QmZq5YDcwdi3Zwda3nhxNyAfgCTa6ngh2YprffatR4SGkF': No scheme supplied. Perhaps you meant http://QmZq5YDcwdi3Zwda3nhxNyAfgCTa6ngh2YprffatR4SGkF?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 432, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'QmZq5YDcwdi3Zwda3nhxNyAfgCTa6ngh2YprffatR4SGkF': No scheme supplied. Perhaps you meant http://QmZq5YDcwdi3Zwda3nhxNyAfgCTa6ngh2YprffatR4SGkF?
2025-01-12 17:09:49,181 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:09:49,487 - ERROR - An error occurred: Invalid URL 'QmYKMQCZEkqtfwUdgf2KQaw9YeCnKYffA9BNv6YuTH1iPU': No scheme supplied. Perhaps you meant http://QmYKMQCZEkqtfwUdgf2KQaw9YeCnKYffA9BNv6YuTH1iPU?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 432, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'QmYKMQCZEkqtfwUdgf2KQaw9YeCnKYffA9BNv6YuTH1iPU': No scheme supplied. Perhaps you meant http://QmYKMQCZEkqtfwUdgf2KQaw9YeCnKYffA9BNv6YuTH1iPU?
2025-01-12 17:09:49,488 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:09:52,047 - ERROR - An error occurred: Invalid URL 'QmXqvBtttkGhaFwq3Vi61omMqHLRacfvtjKaZ98arsPihW': No scheme supplied. Perhaps you meant http://QmXqvBtttkGhaFwq3Vi61omMqHLRacfvtjKaZ98arsPihW?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 432, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'QmXqvBtttkGhaFwq3Vi61omMqHLRacfvtjKaZ98arsPihW': No scheme supplied. Perhaps you meant http://QmXqvBtttkGhaFwq3Vi61omMqHLRacfvtjKaZ98arsPihW?
2025-01-12 17:09:52,048 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:09:52,654 - INFO - Application is stopping. This might take a moment.
2025-01-12 17:09:52,654 - INFO - Application.stop() complete
2025-01-12 17:11:35,532 - INFO - Starting bot...
2025-01-12 17:11:36,597 - INFO - Application started
2025-01-12 17:11:48,677 - INFO - Starting bot...
2025-01-12 17:11:49,631 - INFO - Application started
2025-01-12 17:11:57,384 - INFO - Subscribing to new token creation events...
2025-01-12 17:13:19,857 - ERROR - An error occurred: Invalid URL 'QmVWXdDkYWYGXnSneUnkH7d4gmUiawAEkz9YsnJmjJ39eY': No scheme supplied. Perhaps you meant http://QmVWXdDkYWYGXnSneUnkH7d4gmUiawAEkz9YsnJmjJ39eY?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 433, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'QmVWXdDkYWYGXnSneUnkH7d4gmUiawAEkz9YsnJmjJ39eY': No scheme supplied. Perhaps you meant http://QmVWXdDkYWYGXnSneUnkH7d4gmUiawAEkz9YsnJmjJ39eY?
2025-01-12 17:13:19,859 - ERROR - An error occurred: Invalid URL 'QmUpeiqUyPG94zbaUQY9yaWzU2SpgHibLZF6z68bpPB5Ju': No scheme supplied. Perhaps you meant http://QmUpeiqUyPG94zbaUQY9yaWzU2SpgHibLZF6z68bpPB5Ju?
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 433, in get_ipfs_metadata
    response = requests.get(ipfs_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'QmUpeiqUyPG94zbaUQY9yaWzU2SpgHibLZF6z68bpPB5Ju': No scheme supplied. Perhaps you meant http://QmUpeiqUyPG94zbaUQY9yaWzU2SpgHibLZF6z68bpPB5Ju?
2025-01-12 17:13:38,455 - INFO - Failed to retrieve metadata. Status code: 403
2025-01-12 17:13:38,456 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:14:19,646 - INFO - Application is stopping. This might take a moment.
2025-01-12 17:14:19,646 - INFO - Application.stop() complete
2025-01-12 17:22:24,657 - INFO - Starting bot...
2025-01-12 17:22:25,858 - INFO - Application started
2025-01-12 17:22:42,993 - INFO - Starting bot...
2025-01-12 17:22:44,096 - INFO - Application started
2025-01-12 17:23:29,654 - INFO - Starting bot...
2025-01-12 17:23:30,793 - INFO - Application started
2025-01-12 17:23:50,601 - INFO - Starting bot...
2025-01-12 17:23:51,674 - INFO - Application started
2025-01-12 17:24:13,769 - INFO - Subscribing to new token creation events...
2025-01-12 17:24:29,115 - INFO - Failed to retrieve metadata. Status code: 403
2025-01-12 17:24:29,117 - ERROR - Error adding token data to database: 'NoneType' object has no attribute 'get'
2025-01-12 17:31:30,092 - INFO - Starting bot...
2025-01-12 17:31:31,262 - INFO - Application started
2025-01-12 17:32:32,625 - INFO - Subscribing to new token creation events...
2025-01-12 17:36:00,894 - INFO - Failed to retrieve metadata. Status code: 403
2025-01-12 17:37:15,643 - INFO - Failed to retrieve metadata. Status code: 403
2025-01-12 17:38:51,903 - INFO - Token update - {count}
2025-01-12 17:41:43,364 - INFO - Failed to retrieve metadata. Status code: 403
2025-01-12 17:42:18,164 - INFO - Starting bot...
2025-01-12 17:42:19,217 - INFO - Application started
2025-01-12 17:42:30,296 - INFO - Starting bot...
2025-01-12 17:42:31,248 - INFO - Application started
2025-01-12 17:42:43,022 - INFO - Subscribing to new token creation events...
2025-01-12 17:43:23,897 - INFO - Failed to retrieve metadata. Status code: 403
2025-01-12 17:45:30,654 - INFO - Successfully unsubscribed from new token creation events.
2025-01-12 17:45:31,883 - INFO - WebSocket task completed or failed.
2025-01-12 18:32:51,490 - ERROR - Error while getting Updates: httpx HTTPError: 
2025-01-12 18:32:51,490 - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpcore/backends/asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/anyio/streams/tls.py", line 204, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/anyio/streams/tls.py", line 147, in _call_sslobject_method
    data = await self.transport_stream.receive()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 1300, in receive
    raise self._protocol.exception from None
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpcore/_async/http11.py", line 112, in handle_async_request
    raise exc
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpcore/_async/http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpcore/_async/http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpcore/_async/http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpcore/backends/asyncio.py", line 31, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 183, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/ext/_updater.py", line 600, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/ext/_updater.py", line 327, in polling_action_cb
    raise exc
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/ext/_updater.py", line 312, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 524, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/_bot.py", line 334, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/_bot.py", line 3584, in get_updates
    await self._post(
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/_bot.py", line 422, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 306, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/_bot.py", line 453, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 288, in _request_wrapper
    raise exc
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 274, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 204, in do_request
    raise NetworkError(f"httpx HTTPError: {err}") from err
telegram.error.NetworkError: httpx HTTPError: 
2025-01-12 19:07:04,000 - INFO - Starting bot...
2025-01-12 19:07:04,973 - INFO - Application started
2025-01-12 19:07:17,382 - INFO - Starting bot...
2025-01-12 19:07:18,524 - INFO - Application started
2025-01-12 19:07:32,102 - INFO - Subscribing to new token creation events...
2025-01-12 19:07:36,096 - ERROR - Error adding token data to database: send_telegram_message_if_same_twitter_connected() takes 4 positional arguments but 5 were given
2025-01-12 19:07:37,014 - INFO - Successfully unsubscribed from new token creation events.
2025-01-12 19:07:39,888 - INFO - WebSocket task completed or failed.
2025-01-12 19:08:59,532 - INFO - Starting bot...
2025-01-12 19:09:00,579 - INFO - Application started
2025-01-12 19:09:10,450 - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/ext/_application.py", line 1063, in process_update
    await coroutine
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 312, in get_chat_ids
    data = get_bot_updates().json()
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'json'
2025-01-12 19:10:24,194 - INFO - Starting bot...
2025-01-12 19:10:25,154 - INFO - Application started
2025-01-12 19:11:53,171 - INFO - Starting bot...
2025-01-12 19:11:54,507 - INFO - Application started
2025-01-12 19:13:11,537 - INFO - Starting bot...
2025-01-12 19:13:12,606 - INFO - Application started
2025-01-12 19:13:46,816 - INFO - Starting bot...
2025-01-12 19:13:48,231 - INFO - Application started
2025-01-12 19:20:27,759 - INFO - Starting bot...
2025-01-12 19:20:28,951 - INFO - Application started
2025-01-12 19:59:17,273 - INFO - Starting bot...
2025-01-12 19:59:18,252 - INFO - Application started
2025-01-12 20:04:38,480 - INFO - Starting bot...
2025-01-12 20:04:39,370 - INFO - Application started
2025-01-12 20:05:07,102 - INFO - Subscribing to new token creation events...
2025-01-12 20:05:08,853 - ERROR - Error adding token data to database: send_telegram_message_if_same_twitter_connected() takes 4 positional arguments but 5 were given
2025-01-12 20:05:18,008 - ERROR - Error adding token data to database: send_telegram_message_if_same_twitter_connected() takes 4 positional arguments but 5 were given
2025-01-12 20:05:18,330 - ERROR - Error adding token data to database: send_telegram_message_if_same_twitter_connected() takes 4 positional arguments but 5 were given
2025-01-12 20:05:21,386 - ERROR - Error adding token data to database: send_telegram_message_if_same_twitter_connected() takes 4 positional arguments but 5 were given
2025-01-12 20:05:25,231 - ERROR - Error adding token data to database: send_telegram_message_if_same_twitter_connected() takes 4 positional arguments but 5 were given
2025-01-12 20:05:28,965 - ERROR - Error adding token data to database: send_telegram_message_if_same_twitter_connected() takes 4 positional arguments but 5 were given
2025-01-12 20:06:47,251 - INFO - Starting bot...
2025-01-12 20:06:48,266 - INFO - Application started
2025-01-12 20:06:52,583 - INFO - Subscribing to new token creation events...
2025-01-12 20:06:57,264 - ERROR - Error adding token data to database: type object 'MemeCoins' has no attribute 'get_tokens_by_twitter_link'
2025-01-12 20:06:57,265 - ERROR - Error adding token data to database: type object 'MemeCoins' has no attribute 'get_tokens_by_twitter_link'
2025-01-12 20:06:59,254 - ERROR - Error adding token data to database: type object 'MemeCoins' has no attribute 'get_tokens_by_twitter_link'
2025-01-12 20:06:59,254 - ERROR - Error adding token data to database: type object 'MemeCoins' has no attribute 'get_tokens_by_twitter_link'
2025-01-12 20:07:05,432 - ERROR - Error adding token data to database: type object 'MemeCoins' has no attribute 'get_tokens_by_twitter_link'
2025-01-12 20:07:05,768 - INFO - Application is stopping. This might take a moment.
2025-01-12 20:07:05,769 - INFO - Application.stop() complete
2025-01-12 20:09:14,521 - INFO - Starting bot...
2025-01-12 20:09:15,624 - INFO - Application started
2025-01-12 20:09:21,867 - INFO - Subscribing to new token creation events...
2025-01-12 20:11:36,133 - INFO - Failed to retrieve metadata. Status code: 403
2025-01-12 20:11:36,133 - INFO - ipfs URL: https://4everland.io/ipfs/QmfSuXJuGboyq88a8nFmoqYF39HjmDuFsTQqtFsWy8iUzr
2025-01-12 20:12:19,450 - INFO - Token update - {count}
2025-01-12 20:17:35,086 - INFO - Starting bot...
2025-01-12 20:17:36,110 - INFO - Application started
2025-01-12 20:17:47,629 - INFO - Subscribing to new token creation events...
2025-01-12 20:21:08,778 - INFO - Starting bot...
2025-01-12 20:21:10,063 - INFO - Application started
2025-01-12 20:21:19,175 - INFO - Subscribing to new token creation events...
2025-01-12 20:26:43,113 - INFO - Starting bot...
2025-01-12 20:26:44,090 - INFO - Application started
2025-01-12 20:26:51,244 - INFO - Subscribing to new token creation events...
2025-01-12 20:27:44,099 - INFO - Failed to retrieve metadata. Status code: 403
2025-01-12 20:27:44,099 - INFO - ipfs URL: https://4everland.io/ipfs/QmP3zZ6E8ggJ4Qsb3xHHxFgyFDjJLWrDP3PtSGJnQKqoQN
2025-01-12 20:30:21,057 - INFO - Starting bot...
2025-01-12 20:30:22,013 - INFO - Application started
2025-01-12 20:30:25,937 - INFO - Subscribing to new token creation events...
2025-01-12 20:32:18,097 - INFO - Starting bot...
2025-01-12 20:32:19,258 - INFO - Application started
2025-01-12 20:32:48,632 - INFO - Subscribing to new token creation events...
2025-01-12 20:36:45,169 - INFO - Starting bot...
2025-01-12 20:36:46,294 - INFO - Application started
2025-01-12 20:36:55,244 - INFO - Subscribing to new token creation events...
2025-01-12 20:39:50,505 - INFO - Starting bot...
2025-01-12 20:39:51,673 - INFO - Application started
2025-01-12 20:39:53,697 - INFO - Subscribing to new token creation events...
2025-01-12 21:02:00,276 - INFO - Starting bot...
2025-01-12 21:02:01,425 - INFO - Application started
2025-01-12 21:02:11,450 - INFO - Subscribing to new token creation events...
2025-01-13 14:05:17,371 - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/ext/_application.py", line 1063, in process_update
    await coroutine
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 239, in set_duplicate_count
    send_telegram_message_to_bot(f"Duplicate count has been set to {Config.default_Multiplicity_value}.", parse_mode='Markdown')
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Config' has no attribute 'default_Multiplicity_value'
2025-01-13 14:40:12,041 - ERROR - Error subscribing to WebSocket: name 'TOKEN_NAMES_LIST' is not defined
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 53, in subscribe_to_tokens
    send_telegram_message_to_bot(f"*Successfully subscribed to new token creation events for token names:\n\n* {', '.join(TOKEN_NAMES_LIST)}", parse_mode='Markdown')
                                                                                                                          ^^^^^^^^^^^^^^^^
NameError: name 'TOKEN_NAMES_LIST' is not defined
2025-01-13 14:40:16,958 - ERROR - Error subscribing to WebSocket: name 'TOKEN_NAMES_LIST' is not defined
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 53, in subscribe_to_tokens
    send_telegram_message_to_bot(f"*Successfully subscribed to new token creation events for token names:\n\n* {', '.join(TOKEN_NAMES_LIST)}", parse_mode='Markdown')
                                                                                                                          ^^^^^^^^^^^^^^^^
NameError: name 'TOKEN_NAMES_LIST' is not defined
2025-01-13 14:44:04,903 - ERROR - Error subscribing to WebSocket: name 'TOKEN_NAMES_LIST' is not defined
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 53, in subscribe_to_tokens
    send_telegram_message_to_bot(f"*Successfully subscribed to new token creation events for token names:\n\n* {', '.join(TOKEN_NAMES_LIST)}", parse_mode='Markdown')
                                                                                                                          ^^^^^^^^^^^^^^^^
NameError: name 'TOKEN_NAMES_LIST' is not defined
2025-01-13 14:44:09,306 - ERROR - Error subscribing to WebSocket: name 'TOKEN_NAMES_LIST' is not defined
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 53, in subscribe_to_tokens
    send_telegram_message_to_bot(f"*Successfully subscribed to new token creation events for token names:\n\n* {', '.join(TOKEN_NAMES_LIST)}", parse_mode='Markdown')
                                                                                                                          ^^^^^^^^^^^^^^^^
NameError: name 'TOKEN_NAMES_LIST' is not defined
2025-01-13 14:46:01,870 - ERROR - Error subscribing to WebSocket: 'module' object is not callable
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 71, in subscribe_to_tokens
    asyncio.create_task(add_token_data_into_database (token_name, token_symbol,contract_address,developer,url_link))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
2025-01-13 14:46:07,990 - ERROR - Error subscribing to WebSocket: 'module' object is not callable
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 71, in subscribe_to_tokens
    asyncio.create_task(add_token_data_into_database (token_name, token_symbol,contract_address,developer,url_link))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
2025-01-13 14:49:07,367 - ERROR - Error subscribing to WebSocket: 'module' object is not callable
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 72, in subscribe_to_tokens
    asyncio.create_task(add_token_data_into_database (token_name, token_symbol,contract_address,developer,url_link))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
2025-01-13 14:51:33,505 - ERROR - Error subscribing to WebSocket: 'module' object is not callable
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 71, in subscribe_to_tokens
    asyncio.create_task(add_token_data_into_database (token_name, token_symbol,contract_address,developer,url_link))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
2025-01-13 14:53:11,204 - ERROR - Error subscribing to WebSocket: 'module' object is not callable
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 71, in subscribe_to_tokens
    asyncio.create_task(add_token_data_into_database (token_name, token_symbol,contract_address,developer,url_link))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
2025-01-13 14:54:19,979 - ERROR - Error subscribing to WebSocket: 'module' object is not callable
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 70, in subscribe_to_tokens
    asyncio.create_task(add_token_data_into_database (token_name, token_symbol,contract_address,developer,url_link))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
2025-01-13 14:54:26,565 - ERROR - Error subscribing to WebSocket: 'module' object is not callable
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 70, in subscribe_to_tokens
    asyncio.create_task(add_token_data_into_database (token_name, token_symbol,contract_address,developer,url_link))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
2025-01-13 15:33:34,890 - ERROR - Error subscribing to WebSocket: module 'telegram_bot.methods' has no attribute 'check_token_name_available_in_the_list_and_send_telegram_message'
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 76, in subscribe_to_tokens
    asyncio.create_task(methods.check_token_name_available_in_the_list_and_send_telegram_message(token_name,token_symbol,contract_address,developer, url_link))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'telegram_bot.methods' has no attribute 'check_token_name_available_in_the_list_and_send_telegram_message'
2025-01-13 15:33:40,725 - ERROR - Error subscribing to WebSocket: module 'telegram_bot.methods' has no attribute 'check_token_name_available_in_the_list_and_send_telegram_message'
Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 76, in subscribe_to_tokens
    asyncio.create_task(methods.check_token_name_available_in_the_list_and_send_telegram_message(token_name,token_symbol,contract_address,developer, url_link))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'telegram_bot.methods' has no attribute 'check_token_name_available_in_the_list_and_send_telegram_message'
2025-01-13 15:40:19,762 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:40:20,136 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:40:21,936 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:40:27,985 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:40:30,306 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:40:36,009 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:40:36,395 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:40:36,784 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:40:46,084 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:40:53,707 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:40:57,218 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:41:10,129 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:41:11,629 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:41:13,208 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:41:18,863 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:41:24,208 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:41:37,374 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:41:37,974 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:41:38,597 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:41:42,908 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:41:45,064 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:41:57,554 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:41:58,164 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:41:58,714 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:42:00,320 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:42:03,964 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:42:10,864 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:42:12,076 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:42:13,854 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:42:19,376 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:42:22,487 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:42:26,276 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:42:35,353 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:42:38,524 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:42:44,159 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:42:47,229 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:42:50,405 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:42:53,679 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:49:36,717 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:49:39,680 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:49:42,646 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:49:43,746 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:49:44,331 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:49:54,541 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:49:57,821 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:50:13,485 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:50:19,015 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:50:22,394 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:50:27,004 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:50:31,510 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:50:35,194 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:50:38,574 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:50:43,591 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:51:27,520 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:51:31,402 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:51:35,712 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:51:38,682 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:51:41,753 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:51:44,679 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:51:47,277 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:51:51,380 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:51:54,451 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:51:57,216 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:52:03,464 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:52:06,538 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:52:09,709 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:52:12,576 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:52:15,853 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:52:19,089 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:52:21,997 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:52:25,273 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:52:28,237 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:52:31,119 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:53:01,011 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:53:06,745 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:53:09,920 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:53:13,914 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:53:18,009 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:53:23,848 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:53:26,714 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:53:29,478 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:53:32,756 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:53:36,031 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:53:39,017 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:53:41,971 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:53:45,248 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:53:48,013 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 15:53:51,079 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:04:22,361 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:04:29,458 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:04:33,213 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:04:34,836 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:04:40,369 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:04:42,103 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:04:42,747 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:04:43,714 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:04:58,470 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:04:59,081 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:05:06,259 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:05:09,293 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:05:09,870 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:05:10,371 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:05:14,182 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:05:15,804 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:05:18,882 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:05:19,237 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:05:20,940 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:05:36,840 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:05:37,763 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:05:39,496 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:26:29,766 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:26:33,694 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:26:37,761 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:26:38,173 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:26:48,505 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:26:51,650 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:26:57,639 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:27:07,274 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:27:09,206 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:27:14,039 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:27:19,240 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:27:21,263 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:27:21,686 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:27:24,517 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:27:31,673 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:27:31,673 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:27:44,453 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:27:44,806 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:27:44,807 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:27:44,807 - ERROR - Error adding token data to database: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:27:52,239 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:27:57,551 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:27:57,552 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:06,470 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:06,819 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:06,819 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:06,820 - ERROR - Error adding token data to database: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:16,375 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:16,375 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:16,376 - ERROR - Error adding token data to database: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:19,581 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:19,964 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:19,964 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:20,297 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:20,297 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:22,119 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:22,119 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:22,618 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:22,618 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:32,444 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:37,190 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:37,573 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:37,573 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:45,220 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:45,220 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:46,073 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:46,073 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:46,073 - ERROR - Error adding token data to database: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:48,863 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:49,429 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:49,429 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:49,818 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:49,818 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:52,429 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:52,429 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:28:52,429 - ERROR - Error adding token data to database: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:53,751 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:28:53,751 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:01,518 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:01,518 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:02,532 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:02,532 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:12,006 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:12,419 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:12,419 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:12,765 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:12,765 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:13,074 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:13,074 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:17,419 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:17,420 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:18,132 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:18,132 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:26,275 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:26,275 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:36,990 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:36,990 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:37,298 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:37,298 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:39,632 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:39,632 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:39,632 - ERROR - Error adding token data to database: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:42,936 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:43,309 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:43,309 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:45,909 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:45,910 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:50,243 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:50,243 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:50,587 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:50,587 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:53,379 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:29:58,299 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:29:58,299 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:30:02,265 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:30:02,266 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:30:02,699 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:30:02,699 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:30:02,700 - ERROR - Error adding token data to database: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:30:03,987 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:30:03,988 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:30:07,745 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:30:07,745 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:30:07,746 - ERROR - Error adding token data to database: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:30:10,578 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:30:10,932 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:30:10,932 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:30:15,321 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:30:15,321 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:30:23,311 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:30:25,022 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:30:25,022 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:34:16,234 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:16,234 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:34:17,474 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:17,474 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:34:21,542 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:21,543 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:34:25,809 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:25,809 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:34:25,810 - ERROR - Error adding token data to database: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:26,375 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:26,375 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:34:26,997 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:26,998 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:34:28,631 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:28,631 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:34:28,632 - ERROR - Error adding token data to database: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:32,676 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:32,677 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:34:33,399 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:33,399 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:34:33,400 - ERROR - Error adding token data to database: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:36,699 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:36,700 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:34:36,700 - ERROR - Error adding token data to database: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:39,744 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:39,744 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:34:51,634 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:51,635 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:34:55,969 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:34:55,969 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:34:55,970 - ERROR - Error adding token data to database: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:35:02,725 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:35:02,725 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:35:09,159 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:35:09,159 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:35:13,624 - ERROR - Error checking token availability: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:35:13,624 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:35:13,625 - ERROR - Error adding token data to database: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:36:48,120 - ERROR - Error time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:36:50,587 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:36:50,961 - ERROR - Error time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:36:53,251 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:36:53,606 - ERROR - Error time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:36:55,912 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:36:56,604 - ERROR - Error time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:36:59,088 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:37:01,605 - ERROR - Error time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:37:04,208 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:37:04,210 - ERROR - Error time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:38:36,285 - ERROR - Error time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:38:39,549 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:38:39,551 - ERROR - Error time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:39:59,427 - ERROR - Error time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:40:01,783 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:40:02,168 - ERROR - Error time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:40:04,545 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:40:04,547 - ERROR - Error time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:42:07,040 - ERROR - Error in time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:42:09,582 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:42:10,746 - ERROR - Error in time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:42:14,292 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:42:14,646 - ERROR - Error in time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:43:32,692 - ERROR - Error in time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:43:34,987 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:43:35,331 - ERROR - Error in time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:43:37,752 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:43:38,198 - ERROR - Error in time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:43:40,520 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:43:40,522 - ERROR - Error in time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:43:43,409 - ERROR - Error in time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:43:45,944 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:43:46,301 - ERROR - Error in time_since_added method: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2025-01-13 16:47:02,972 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:47:06,412 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:47:09,626 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:47:12,700 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:47:15,565 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:47:18,433 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:47:21,402 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:47:24,375 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:47:27,137 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:47:32,362 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:47:35,329 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:47:37,992 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:49:13,636 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:49:16,547 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:49:19,515 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:49:25,105 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:49:33,400 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:49:36,472 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:49:39,441 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:49:42,207 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:49:44,972 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:49:47,838 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:49:58,181 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:59:05,681 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:59:17,303 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:59:40,163 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:59:44,129 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 16:59:52,618 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:00:07,913 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:00:12,064 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:00:17,476 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:00:28,571 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:00:31,131 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:02:16,501 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:02:19,576 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:02:24,899 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:02:27,765 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:02:30,466 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:02:33,193 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:02:36,060 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:02:38,927 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:02:41,794 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:02:44,559 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:02:47,324 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:02:50,191 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:04:12,853 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:04:15,697 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:04:18,565 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:04:21,432 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:04:24,094 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:04:27,576 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:04:35,358 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:04:43,143 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:04:53,511 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:04:59,119 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:05:01,778 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:05:13,042 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:05:15,910 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:05:21,234 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:05:24,101 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:05:26,763 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:05:29,734 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:05:40,386 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:05:43,250 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:05:46,116 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:05:48,821 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:05:51,646 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:05:54,207 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:12:20,446 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:12:28,740 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:12:33,246 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:12:41,949 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:12:44,715 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:12:47,226 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:12:49,835 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:12:52,599 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:12:55,364 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:12:58,128 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:13:06,116 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:13:09,290 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:13:20,145 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:13:22,910 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:13:26,186 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:13:29,053 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:13:31,817 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:13:34,685 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:13:37,654 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
2025-01-13 17:13:43,698 - ERROR - Error subscribing to WebSocket: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
Traceback (most recent call last):
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1314, in close_connection
    await self.transfer_data_task
  File "/usr/lib/python3.12/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 385, in __wakeup
    future.result()
  File "/usr/lib/python3.12/asyncio/futures.py", line 198, in result
    raise exc
  File "/usr/lib/python3.12/asyncio/tasks.py", line 316, in __step_run_and_handle_result
    result = coro.throw(exc)
             ^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 968, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1038, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1113, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1170, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/websockets/legacy/framing.py", line 69, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/streams.py", line 752, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.12/asyncio/streams.py", line 545, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.12/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 385, in __wakeup
    future.result()
  File "/usr/lib/python3.12/asyncio/futures.py", line 198, in result
    raise exc
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/isha/My Git Hub Projects/Pumpfun Telegram Bot/pump-fun-tracking-telegram-bot-project/telegram_bot/bot.py", line 57, in subscribe_to_tokens
    async for message in websocket:
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 497, in __aiter__
    yield await self.recv()
          ^^^^^^^^^^^^^^^^^
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/home/isha/Documents/newTelegramBot/my_project/venv/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
2025-01-13 17:13:50,867 - ERROR - Error checking tokens and sending message: name 'token_names' is not defined
